apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello camel"

      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Build JAR
        uses: docker://maven:3.9.6-eclipse-temurin-17
        shell: sh
        run: |
          mmvn clean install -Dquickly

      - name: Show built files in target dir
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          find ./target